### ISSUE TITLE
Problems plotting across date line

### ISSUE THREAD

**Issue by tommyclay** [BirdLifeInternational/track2kba#33]
Hi Martin,

I occasionally get an error (pasted below) when I use the mapTrips() function. I realize this happens only when I use trips that cross the International Date Line (e.g. from New Zealand). So it might be worth including something (e.g. longitude transformation) that allows plotting of trips across this line, if not in the code already.

Error: Mapping should be created with `aes()` or `aes_()`.

Best,

Tommy

**Comment by steffenoppel** [comment]
Thanks Tommy, we already have code (L. 55-65) to transform the Longitude to wrap around the dateline, but maybe this doesn't work if you have a trip that circumnavigates earth? Could you send us a minimum example to replicate the error? Because there is an aes() statement in this plotting function, so I don't see where the error comes from.

**Comment by tommyclay** [comment]
Hi Steffen, 

Apologies for the delay. The problem seems to occur when there are some trips that cross the dateline and some that don't - which is typical of some albatross species that breed in islands off New Zealand, but perhaps other species as well. I have sent some example data directly to you and Martin to have a look. 

Best,

Tommy

**Comment by MartinBeal** [comment]
This is taken care of. Thanks for bringing it to our attention, Tommy.

**Comment by tommyclay** [comment]
Great, thanks!
