### ISSUE TITLE
possible improvement: chose parameters for colour aes in mapTrips

### ISSUE THREAD

**Issue by VirginiaMorera** [BirdLifeInternational/track2kba#35]
Hi

I find it would be more useful if mapTrips allowed plotting different tripIDs of each individual in different colours, instead of just by whether the trip is complete. 

Happy to make and commit the change if you think it's a good idea.

**Comment by steffenoppel** [comment]
Thanks Virginia. Might be a useful addition. I will let Martin decide because he wrote the function, but it should be straightforward to change lines 70 and 95 to:
col = .data$tripID, linetype= .data$complete)

Might need some work to extract the ID from tripID, or change L. 190/192 in tripSplit to use sep="_" and then simply str_split with paterrn="_". Otherwise you will end up with too many confusing and not very different colours...

If we can make this to show only 3-5 colours (for trips 1-5, same for each individual) then that's good.

**Comment by MartinBeal** [comment]
Sounds like a good idea to me.

Could be good to have an argument to allow users to choose whether to
visualize return trip colors or tripID colors.

Virginia, feel free to suggest a code change and I'll be happy to double
check it.

**Comment by VirginiaMorera** [comment]
Ok, will try to figure something out that does restart colours at every facet, to avoid the issue with the colours that Steffen was mentioning!
