### ISSUE TITLE
update on indEffectTest possible?

### ISSUE THREAD

**Issue by steffenoppel** [BirdLifeInternational/track2kba#38]
Just [saw a new paper](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.13339) which claims to have developed two novel metrics, the spatial individual specialization index (SpatIS) and the spatial individual complementary specialization index (SpatICS). Not sure we want to try and adopt these? Haven't checked out the paper or the index calculation, but am suspicious that they work with n=10 individuals, which seems a bit slim for widespread conclusions about individual specialisation...

**Comment by VirginiaMorera** [comment]
Ah, cheers! I've skimmed through it and it seems that SpatIS uses the overlap of an individual KDE and the entire population, while SpatICS uses the overlap between one individual and the population without that individual. I think the difference between their approach and ours is that they don't consider different "trips" to compare variability among same-individual trips and different-individual trips, it just considers the space use of each individual as a whole. This has the potential pitfall of being biased when one individual has been sampled for longer than the other in the population, but it might still be a good addition if we want to make this method useful for animals that are not central place foragers. However, whenever the movement can be split in trips, I think our approach is more accurate... But I will put the article in my reading list to see if there's something else there! 

In any case, I already have a new version of the function that does not use iid kernels, but autocorrelated kernels from the ctmm package, since it was a requirement of the reviewers. I'm finishing some power tests and putting it to work with a large dataset to see how it performs, but it will be ready soon in case Martin wants to add it to the package at some point.
