### ISSUE TITLE
repAssess - Nloop error

### ISSUE THREAD

**Issue by pecard** [BirdLifeInternational/track2kba#39]
Hi, repAssess seems to require a minimum N of indivíduals to run.
I'm testing with NIDs = 2
 
```
unique(tracks$ID)
[1] "A" "B"
```
and getting:

`Error in seq.default(1, (NIDs - 3), 1) : wrong sign in 'by' argument`

repAssess will not run when N<3?

**Comment by steffenoppel** [comment]
Dear Paulo, the purpose of the function is to assess whether your sample is representative for a population. This is evidently not the case with n=2, and the function therefore does not run with n=2. The help file of the function clearly states "NOTE: this function does not work with fewer than 4 IDs (tracks or individual animals).". You will need a larger sample size to assess representativeness.

**Comment by pecard** [comment]
Thanks, understood. but 4 ? would be nice to run as an exercise...

**Comment by MartinBeal** [comment]
More specifically, the way the function calculates the representativeness
estimate is by re-sampling the sample of tracks. To be able to re-sample
enough times to get a stable value, we need to draw sub-samples smaller
than the maximum N (i.e. there is only one possible set of 10 tracks in a
sample of N = 10). So, when the sample size is < 20 tracks, the number of
sub-samples drawn is N - 3, to ensure that a high number of track
combinations are possible. So 4 is the minimum because 4 - 3 = 1. The
result for this analysis would be nonsense, but this is just the
mathematical minimum.

Hope that makes sense.

**Comment by pecard** [comment]
with N<4 a warning on lack of representativeness and suppressing the re-sampling process...

**Comment by MartinBeal** [comment]
If N < 4 then the function does not work.
