### ISSUE TITLE
Matching package dependency

### ISSUE THREAD

**Issue by MartinBeal** [BirdLifeInternational/track2kba#41]
As you can see [here](https://cran.r-project.org/web/packages/Matching/index.html), the Matching package is not currently available on CRAN. Because the track2KBA::indEffectTest() function uses Matching::ks.boot(), our package is at risk of being archived.

@VirginiaMorera can you think of an alternative method for running this bootstrap that wouldn't require the Matching package?

We have until April 23rd to fix this and pass the CRAN tests or our package will be removed from CRAN.

**Comment by steffenoppel** [comment]
Could we simply replace it with 'ks.test' or provide a bootstrapped ks-test that does not require a deprecated package, e.g. adopting the code from [this thread](https://stats.stackexchange.com/questions/472379/bootstrap-ks-2-sample-test)?

**Comment by MartinBeal** [comment]
'Matching' has become available again, so I am waiting to hear back from CRAN maintainers on whether or not we need to make any further changes. Worst case, I've made a brance 'no_match_depend' which replaces the bootstrapped ks.test with a simple ks.test which can be used in case we need it.

Will let you know what CRAN says.

**Comment by VirginiaMorera** [comment]
Sorry I haven't been able to look into this until now. The reason I used the matching package ks test is that it does not assume independence of samples (since the kernels involved in the within individual overlaps will also be involved in the between individual overlaps) and also does not assume continuous distributions (since the overlap values are percentages). I seem to remember there was not a big difference between the bootstrapped KS test and the normal KS test, but it seemed more appropriate. Let's see if matching can still be a solution, if not, I'd at least issue a warning with the result if we use the non bootstrapped ks test? I'll try to think of an alternative way of doing this

**Comment by MartinBeal** [comment]
OK so just FYI our package has been taken off CRAN until we pass the checks. I re-submitted it last friday but it came back with a tiny note so I have fixed that and re-submitted today. Hopefully should be back online late this week.

**Comment by MartinBeal** [comment]
Ok, we're back online. For now no need to worry about removing the Matching dependency, as that package appears to also be actively maintained.
